# Generated by Django 4.2 on 2023-06-22 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="base_colorpalette",
            old_name="secondary",
            new_name="d_prime",
        ),
    ]
