# Generated by Django 4.2 on 2023-06-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_prime_text_base_colorpalette_dark_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="base_colorpalette",
            old_name="background_text",
            new_name="light_text",
        ),
    ]
