# Generated by Django 4.2 on 2023-06-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_background_text_base_colorpalette_light_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="base_colorpalette",
            name="transparent",
        ),
    ]
