# Generated by Django 4.2.3 on 2023-07-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_base_colorpalette_transparent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="base_colorpalette",
            name="dark_text",
            field=models.CharField(default="#404040", max_length=25),
        ),
        migrations.AlterField(
            model_name="base_colorpalette",
            name="light_text",
            field=models.CharField(default="#eeeeee", max_length=25),
        ),
    ]
