# Generated by Django 4.2.3 on 2023-11-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='alt',
            field=models.CharField(default='image', max_length=256),
        ),
    ]
